"""order tables

Revision ID: cce062366c38
Revises: 9565a25dece9
Create Date: 2026-10-04 19:17:15.749754

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "cce062366c38"
down_revision: str | Sequence[str] | None = "9565a25dece9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("order_number", sa.String(length=20), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING_PAYMENT",
                "CONFIRMED",
                "PROCESSING",
                "SHIPPED",
                "DELIVERED",
                "CANCELLED",
                name="orderstatus",
                native_enum=False,
                length=20,
            ),
            server_default="PENDING_PAYMENT",
            nullable=False,
        ),
        sa.Column(
            "payment_status",
            sa.Enum(
                "UNPAID",
                "PAID",
                "REFUND_PENDING",
                "REFUNDED",
                "PARTIALLY_REFUNDED",
                "FAILED",
                name="paymentstatus",
                native_enum=False,
                length=20,
            ),
            server_default="UNPAID",
            nullable=False,
        ),
        sa.Column("currency", sa.String(length=3), server_default="INR", nullable=False),
        sa.Column("subtotal_paise", sa.BigInteger(), nullable=False),
        sa.Column("discount_paise", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("shipping_paise", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("tax_paise", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column("total_paise", sa.BigInteger(), nullable=False),
        sa.Column("coupon_code", sa.String(length=30), nullable=True),
        sa.Column("shipping_address", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("contact_email", sa.String(length=254), nullable=False),
        sa.Column("contact_phone", sa.String(length=16), nullable=True),
        sa.Column("customer_note", sa.Text(), nullable=True),
        sa.Column("courier_name", sa.String(length=60), nullable=True),
        sa.Column("tracking_number", sa.String(length=60), nullable=True),
        sa.Column("tracking_url", sa.String(length=500), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "placed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("shipped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_reason", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.UUID(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("currency = 'INR'", name=op.f("ck_orders_currency_inr")),
        sa.CheckConstraint(
            "payment_status IN ('UNPAID', 'PAID', 'REFUND_PENDING', 'REFUNDED', 'PARTIALLY_REFUNDED', 'FAILED')",
            name=op.f("ck_orders_payment_status"),
        ),
        sa.CheckConstraint(
            "status <> 'PENDING_PAYMENT' OR expires_at IS NOT NULL",
            name=op.f("ck_orders_pending_has_expiry"),
        ),
        sa.CheckConstraint(
            "status IN ('PENDING_PAYMENT', 'CONFIRMED', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED')",
            name=op.f("ck_orders_status"),
        ),
        sa.CheckConstraint(
            "discount_paise <= subtotal_paise", name=op.f("ck_orders_discount_within_subtotal")
        ),
        sa.CheckConstraint(
            "subtotal_paise >= 0 AND discount_paise >= 0 AND shipping_paise >= 0 AND tax_paise >= 0 AND total_paise >= 0",
            name=op.f("ck_orders_amounts_not_negative"),
        ),
        sa.CheckConstraint("tax_paise <= total_paise", name=op.f("ck_orders_tax_within_total")),
        sa.CheckConstraint(
            "total_paise = subtotal_paise - discount_paise + shipping_paise",
            name=op.f("ck_orders_total_adds_up"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_orders_user_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("order_number", name=op.f("uq_orders_order_number")),
        sa.UniqueConstraint(
            "user_id", "idempotency_key", name=op.f("uq_orders_user_id_idempotency_key")
        ),
    )
    op.create_index("ix_orders_created_at", "orders", ["created_at"], unique=False)
    op.create_index("ix_orders_payment_status", "orders", ["payment_status"], unique=False)
    op.create_index(
        "ix_orders_pending_expires_at",
        "orders",
        ["expires_at"],
        unique=False,
        postgresql_where=sa.text("status = 'PENDING_PAYMENT'"),
    )
    op.create_index(
        "ix_orders_status_created",
        "orders",
        ["status", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_index(
        "ix_orders_user_created",
        "orders",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    op.create_table(
        "order_status_history",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("order_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "from_status",
            sa.Enum(
                "PENDING_PAYMENT",
                "CONFIRMED",
                "PROCESSING",
                "SHIPPED",
                "DELIVERED",
                "CANCELLED",
                name="orderstatus",
                native_enum=False,
                length=20,
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "PENDING_PAYMENT",
                "CONFIRMED",
                "PROCESSING",
                "SHIPPED",
                "DELIVERED",
                "CANCELLED",
                name="orderstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("changed_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "from_status IN ('PENDING_PAYMENT', 'CONFIRMED', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED')",
            name=op.f("ck_order_status_history_from_status"),
        ),
        sa.CheckConstraint(
            "to_status IN ('PENDING_PAYMENT', 'CONFIRMED', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'CANCELLED')",
            name=op.f("ck_order_status_history_to_status"),
        ),
        sa.ForeignKeyConstraint(
            ["changed_by"],
            ["users.id"],
            name=op.f("fk_order_status_history_changed_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_status_history_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_status_history")),
    )
    op.create_index(
        "ix_order_status_history_order_created",
        "order_status_history",
        ["order_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "order_items",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("order_id", sa.BigInteger(), nullable=False),
        sa.Column("variant_id", sa.BigInteger(), nullable=False),
        sa.Column("product_name", sa.String(length=200), nullable=False),
        sa.Column("variant_label", sa.String(length=100), nullable=False),
        sa.Column("sku", sa.String(length=40), nullable=False),
        sa.Column("image_public_id", sa.String(length=255), nullable=True),
        sa.Column("unit_mrp_paise", sa.BigInteger(), nullable=False),
        sa.Column("unit_price_paise", sa.BigInteger(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("line_total_paise", sa.BigInteger(), nullable=False),
        sa.Column("gst_rate_bp", sa.SmallInteger(), nullable=True),
        sa.Column("configuration", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "gst_rate_bp BETWEEN 0 AND 10000", name=op.f("ck_order_items_gst_rate_range")
        ),
        sa.CheckConstraint(
            "line_total_paise = unit_price_paise * quantity",
            name=op.f("ck_order_items_line_total_adds_up"),
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_order_items_quantity_positive")),
        sa.CheckConstraint(
            "unit_price_paise > 0 AND unit_price_paise <= unit_mrp_paise",
            name=op.f("ck_order_items_price_within_mrp"),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_items_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["product_variants.id"],
            name=op.f("fk_order_items_variant_id_product_variants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_items")),
    )
    op.create_index(op.f("ix_order_items_order_id"), "order_items", ["order_id"], unique=False)
    op.create_index(op.f("ix_order_items_variant_id"), "order_items", ["variant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_order_items_variant_id"), table_name="order_items")
    op.drop_index(op.f("ix_order_items_order_id"), table_name="order_items")
    op.drop_table("order_items")
    op.drop_index("ix_order_status_history_order_created", table_name="order_status_history")
    op.drop_table("order_status_history")
    op.drop_index("ix_orders_user_created", table_name="orders")
    op.drop_index("ix_orders_status_created", table_name="orders")
    op.drop_index(
        "ix_orders_pending_expires_at",
        table_name="orders",
        postgresql_where=sa.text("status = 'PENDING_PAYMENT'"),
    )
    op.drop_index("ix_orders_payment_status", table_name="orders")
    op.drop_index("ix_orders_created_at", table_name="orders")
    op.drop_table("orders")
    # ### end Alembic commands ###
