"""rate limit buckets

Revision ID: a3ca24be4018
Revises: 4d89eb320130
Create Date: 2026-10-04 19:35:20.553147

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a3ca24be4018"
down_revision: str | Sequence[str] | None = "4d89eb320130"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rate_limit_buckets",
        sa.Column("key", sa.String(length=200), nullable=False),
        sa.Column("window_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.CheckConstraint("count > 0", name=op.f("ck_rate_limit_buckets_count_positive")),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_rate_limit_buckets")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rate_limit_buckets")
    # ### end Alembic commands ###
