"""inventory tables

Revision ID: a5a209ef302e
Revises: cce062366c38
Create Date: 2026-10-04 19:17:16.609902

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a5a209ef302e"
down_revision: str | Sequence[str] | None = "cce062366c38"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inventory",
        sa.Column("variant_id", sa.BigInteger(), nullable=False),
        sa.Column("on_hand", sa.Integer(), server_default="0", nullable=False),
        sa.Column("reserved", sa.Integer(), server_default="0", nullable=False),
        sa.Column("low_stock_threshold", sa.Integer(), server_default="3", nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "low_stock_threshold >= 0", name=op.f("ck_inventory_threshold_not_negative")
        ),
        sa.CheckConstraint("on_hand >= 0", name=op.f("ck_inventory_on_hand_not_negative")),
        sa.CheckConstraint(
            "reserved >= 0 AND reserved <= on_hand",
            name=op.f("ck_inventory_reserved_within_on_hand"),
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["product_variants.id"],
            name=op.f("fk_inventory_variant_id_product_variants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("variant_id", name=op.f("pk_inventory")),
    )
    op.create_index(
        "ix_inventory_available",
        "inventory",
        [sa.literal_column("(on_hand - reserved)")],
        unique=False,
    )
    op.create_table(
        "inventory_transactions",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("variant_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "type",
            sa.Enum(
                "RESTOCK",
                "ADJUSTMENT",
                "SALE",
                "RETURN",
                "DAMAGE",
                "CORRECTION",
                name="inventorytransactiontype",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("quantity_delta", sa.Integer(), nullable=False),
        sa.Column("on_hand_after", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.BigInteger(), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "type IN ('RESTOCK', 'ADJUSTMENT', 'SALE', 'RETURN', 'DAMAGE', 'CORRECTION')",
            name=op.f("ck_inventory_transactions_type"),
        ),
        sa.CheckConstraint(
            "type NOT IN ('ADJUSTMENT', 'DAMAGE', 'CORRECTION') OR length(trim(coalesce(note, ''))) > 0",
            name=op.f("ck_inventory_transactions_note_required_for_manual"),
        ),
        sa.CheckConstraint(
            "type NOT IN ('SALE', 'RETURN') OR order_id IS NOT NULL",
            name=op.f("ck_inventory_transactions_order_required_for_sale_return"),
        ),
        sa.CheckConstraint(
            "on_hand_after >= 0", name=op.f("ck_inventory_transactions_on_hand_after_not_negative")
        ),
        sa.CheckConstraint(
            "quantity_delta <> 0", name=op.f("ck_inventory_transactions_delta_not_zero")
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_inventory_transactions_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_inventory_transactions_order_id_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["product_variants.id"],
            name=op.f("fk_inventory_transactions_variant_id_product_variants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_transactions")),
    )
    op.create_index(
        op.f("ix_inventory_transactions_order_id"),
        "inventory_transactions",
        ["order_id"],
        unique=False,
    )
    op.create_index(
        "ix_inventory_transactions_type_created",
        "inventory_transactions",
        ["type", "created_at"],
        unique=False,
    )
    op.create_index(
        "ix_inventory_transactions_variant_created",
        "inventory_transactions",
        ["variant_id", sa.literal_column("created_at DESC")],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_inventory_transactions_variant_created", table_name="inventory_transactions")
    op.drop_index("ix_inventory_transactions_type_created", table_name="inventory_transactions")
    op.drop_index(op.f("ix_inventory_transactions_order_id"), table_name="inventory_transactions")
    op.drop_table("inventory_transactions")
    op.drop_index("ix_inventory_available", table_name="inventory")
    op.drop_table("inventory")
    # ### end Alembic commands ###
