"""catalogue tables

Revision ID: 048e2b4fd70d
Revises: c558d957fd60
Create Date: 2026-10-04 19:17:14.061307

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "048e2b4fd70d"
down_revision: str | Sequence[str] | None = "c558d957fd60"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "brands",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("name", postgresql.CITEXT(), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("logo_public_id", sa.String(length=255), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'", name=op.f("ck_brands_slug_format")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_brands")),
        sa.UniqueConstraint("name", name=op.f("uq_brands_name")),
        sa.UniqueConstraint("slug", name=op.f("uq_brands_slug")),
    )
    op.create_table(
        "categories",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("parent_id", sa.BigInteger(), nullable=True),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("image_public_id", sa.String(length=255), nullable=True),
        sa.Column("sort_order", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'", name=op.f("ck_categories_slug_format")
        ),
        sa.CheckConstraint("parent_id <> id", name=op.f("ck_categories_not_own_parent")),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["categories.id"],
            name=op.f("fk_categories_parent_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint(
            "parent_id",
            "name",
            name=op.f("uq_categories_parent_id_name"),
            postgresql_nulls_not_distinct=True,
        ),
        sa.UniqueConstraint("slug", name=op.f("uq_categories_slug")),
    )
    op.create_index(op.f("ix_categories_parent_id"), "categories", ["parent_id"], unique=False)
    op.create_table(
        "products",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=220), nullable=False),
        sa.Column("brand_id", sa.BigInteger(), nullable=False),
        sa.Column("category_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "gender",
            sa.Enum("MEN", "WOMEN", "UNISEX", "KIDS", name="gender", native_enum=False, length=10),
            server_default="UNISEX",
            nullable=False,
        ),
        sa.Column(
            "frame_type",
            sa.Enum(
                "FULL_RIM", "HALF_RIM", "RIMLESS", name="frametype", native_enum=False, length=20
            ),
            nullable=True,
        ),
        sa.Column(
            "frame_shape",
            sa.Enum(
                "WAYFARER",
                "AVIATOR",
                "ROUND",
                "RECTANGLE",
                "SQUARE",
                "CAT_EYE",
                "OVAL",
                "CLUBMASTER",
                "GEOMETRIC",
                "WRAP",
                name="frameshape",
                native_enum=False,
                length=20,
            ),
            nullable=True,
        ),
        sa.Column(
            "frame_material",
            sa.Enum(
                "METAL",
                "ACETATE",
                "TR90",
                "TITANIUM",
                "PLASTIC",
                "MIXED",
                name="framematerial",
                native_enum=False,
                length=20,
            ),
            nullable=True,
        ),
        sa.Column("model_number", sa.String(length=50), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "specifications",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("hsn_code", sa.String(length=8), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT", "ACTIVE", "INACTIVE", name="productstatus", native_enum=False, length=10
            ),
            server_default="DRAFT",
            nullable=False,
        ),
        sa.Column("is_featured", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "setweight(to_tsvector('english', coalesce(name, '')), 'A') || setweight(to_tsvector('simple', coalesce(model_number, '')), 'A') || setweight(to_tsvector('english', coalesce(description, '')), 'B')",
                persisted=True,
            ),
            nullable=False,
        ),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column("updated_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "frame_material IN ('METAL', 'ACETATE', 'TR90', 'TITANIUM', 'PLASTIC', 'MIXED')",
            name=op.f("ck_products_frame_material"),
        ),
        sa.CheckConstraint(
            "frame_shape IN ('WAYFARER', 'AVIATOR', 'ROUND', 'RECTANGLE', 'SQUARE', 'CAT_EYE', 'OVAL', 'CLUBMASTER', 'GEOMETRIC', 'WRAP')",
            name=op.f("ck_products_frame_shape"),
        ),
        sa.CheckConstraint(
            "frame_type IN ('FULL_RIM', 'HALF_RIM', 'RIMLESS')", name=op.f("ck_products_frame_type")
        ),
        sa.CheckConstraint(
            "gender IN ('MEN', 'WOMEN', 'UNISEX', 'KIDS')", name=op.f("ck_products_gender")
        ),
        sa.CheckConstraint("hsn_code ~ '^[0-9]{4,8}$'", name=op.f("ck_products_hsn_code_digits")),
        sa.CheckConstraint(
            "jsonb_typeof(specifications) = 'array'",
            name=op.f("ck_products_specifications_is_array"),
        ),
        sa.CheckConstraint(
            "slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'", name=op.f("ck_products_slug_format")
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT', 'ACTIVE', 'INACTIVE')", name=op.f("ck_products_status")
        ),
        sa.ForeignKeyConstraint(
            ["brand_id"],
            ["brands.id"],
            name=op.f("fk_products_brand_id_brands"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.id"],
            name=op.f("fk_products_category_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_products_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_products_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("slug", name=op.f("uq_products_slug")),
    )
    op.create_index(op.f("ix_products_brand_id"), "products", ["brand_id"], unique=False)
    op.create_index(op.f("ix_products_category_id"), "products", ["category_id"], unique=False)
    op.create_index(
        "ix_products_created_at", "products", [sa.literal_column("created_at DESC")], unique=False
    )
    op.create_index("ix_products_frame_shape", "products", ["frame_shape"], unique=False)
    op.create_index("ix_products_gender", "products", ["gender"], unique=False)
    op.create_index(
        "ix_products_name_trgm",
        "products",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_index(
        "ix_products_search_vector",
        "products",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "ix_products_status_category", "products", ["status", "category_id"], unique=False
    )
    op.create_table(
        "product_variants",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("sku", sa.String(length=40), nullable=False),
        sa.Column("color_name", sa.String(length=40), nullable=False),
        sa.Column(
            "color_family",
            sa.Enum(
                "BLACK",
                "BROWN",
                "TORTOISE",
                "GOLD",
                "ROSE_GOLD",
                "SILVER",
                "GUNMETAL",
                "GREY",
                "WHITE",
                "BLUE",
                "GREEN",
                "PINK",
                "RED",
                "PURPLE",
                "TRANSPARENT",
                "MULTI",
                name="colorfamily",
                native_enum=False,
                length=20,
            ),
            nullable=True,
        ),
        sa.Column("color_hex", sa.String(length=7), nullable=True),
        sa.Column("size_label", sa.String(length=20), nullable=True),
        sa.Column("lens_width_mm", sa.SmallInteger(), nullable=True),
        sa.Column("bridge_mm", sa.SmallInteger(), nullable=True),
        sa.Column("temple_mm", sa.SmallInteger(), nullable=True),
        sa.Column("mrp_paise", sa.BigInteger(), nullable=False),
        sa.Column("price_paise", sa.BigInteger(), nullable=False),
        sa.Column("weight_grams", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("sort_order", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "color_family IN ('BLACK', 'BROWN', 'TORTOISE', 'GOLD', 'ROSE_GOLD', 'SILVER', 'GUNMETAL', 'GREY', 'WHITE', 'BLUE', 'GREEN', 'PINK', 'RED', 'PURPLE', 'TRANSPARENT', 'MULTI')",
            name=op.f("ck_product_variants_color_family"),
        ),
        sa.CheckConstraint(
            "color_hex ~ '^#[0-9A-Fa-f]{6}$'", name=op.f("ck_product_variants_color_hex_format")
        ),
        sa.CheckConstraint(
            "sku ~ '^[A-Za-z0-9][A-Za-z0-9._/-]*$'", name=op.f("ck_product_variants_sku_format")
        ),
        sa.CheckConstraint(
            "coalesce(lens_width_mm, 1) > 0 AND coalesce(bridge_mm, 1) > 0 AND coalesce(temple_mm, 1) > 0",
            name=op.f("ck_product_variants_dimensions_positive"),
        ),
        sa.CheckConstraint("mrp_paise > 0", name=op.f("ck_product_variants_mrp_positive")),
        sa.CheckConstraint(
            "price_paise > 0 AND price_paise <= mrp_paise",
            name=op.f("ck_product_variants_price_within_mrp"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_variants_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_variants")),
        sa.UniqueConstraint(
            "product_id",
            "color_name",
            "size_label",
            name=op.f("uq_product_variants_product_id_color_name_size_label"),
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(
        op.f("ix_product_variants_product_id"), "product_variants", ["product_id"], unique=False
    )
    op.create_index(
        "uq_product_variants_upper_sku",
        "product_variants",
        [sa.literal_column("upper(sku)")],
        unique=True,
    )
    op.create_table(
        "product_images",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("variant_id", sa.BigInteger(), nullable=True),
        sa.Column("public_id", sa.String(length=255), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=True),
        sa.Column("format", sa.String(length=10), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("bytes", sa.Integer(), nullable=True),
        sa.Column("alt_text", sa.String(length=200), nullable=True),
        sa.Column("sort_order", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("is_primary", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_images_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["variant_id"],
            ["product_variants.id"],
            name=op.f("fk_product_images_variant_id_product_variants"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_images")),
        sa.UniqueConstraint("public_id", name=op.f("uq_product_images_public_id")),
    )
    op.create_index(
        op.f("ix_product_images_product_id"), "product_images", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_product_images_variant_id"), "product_images", ["variant_id"], unique=False
    )
    op.create_index(
        "uq_product_images_one_primary",
        "product_images",
        ["product_id", "variant_id"],
        unique=True,
        postgresql_where=sa.text("is_primary"),
        postgresql_nulls_not_distinct=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_product_images_one_primary",
        table_name="product_images",
        postgresql_where=sa.text("is_primary"),
        postgresql_nulls_not_distinct=True,
    )
    op.drop_index(op.f("ix_product_images_variant_id"), table_name="product_images")
    op.drop_index(op.f("ix_product_images_product_id"), table_name="product_images")
    op.drop_table("product_images")
    op.drop_index("uq_product_variants_upper_sku", table_name="product_variants")
    op.drop_index(op.f("ix_product_variants_product_id"), table_name="product_variants")
    op.drop_table("product_variants")
    op.drop_index("ix_products_status_category", table_name="products")
    op.drop_index("ix_products_search_vector", table_name="products", postgresql_using="gin")
    op.drop_index(
        "ix_products_name_trgm",
        table_name="products",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_index("ix_products_gender", table_name="products")
    op.drop_index("ix_products_frame_shape", table_name="products")
    op.drop_index("ix_products_created_at", table_name="products")
    op.drop_index(op.f("ix_products_category_id"), table_name="products")
    op.drop_index(op.f("ix_products_brand_id"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_categories_parent_id"), table_name="categories")
    op.drop_table("categories")
    op.drop_table("brands")
    # ### end Alembic commands ###
